on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/cache@v3
        id: cached-poetry
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - if: steps.cached-poetry.outputs.cache-hit != 'true'
        run: poetry install
      - run: poetry run ./lint.sh

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/cache@v3
        id: cached-poetry
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - if: steps.cached-poetry.outputs.cache-hit != 'true'
        run: poetry install
      - run: poetry run pytest

  forward:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    if: "!contains(github.event.head_commit.message, '!noforward')"
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: ./src
          fetch-depth: 0
      - name: Get commit details
        id: commit-details
        working-directory: ./src
        run: |
          echo "author=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_OUTPUT
          echo "title=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
      - name: Checkout common AoC repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: AidnAS/advent-of-code
          path: ./dst
      - name: Move files
        run: |
          set -ex
          rm -rf ./dst/2023/frodejac
          mkdir -p ./dst/2023/frodejac
          for path in README.md poetry.lock pyproject.toml .gitignore aoc; do
            mv "./src/$path" "./dst/2023/frodejac/$path"
          done
      - name: Configure git
        working-directory: ./dst
        run: |
          git config --local user.name 'Frode Jacobsen'
          git config --local user.email '6934246+frodejac@users.noreply.github.com'
      - name: Get diff
        working-directory: ./dst
        env:
          author: ${{ steps.commit-details.outputs.author }}
          message: ${{steps.commit-details.outputs.title }}
          sha: ${{ github.sha }}
        run: |
          set -ex
          git add .
          if [[ -n "$(git diff --name-only --cached)" ]]; then
            git commit --author "${author}" -m "${message}" -m "https://github.com/frodejac/aoc-2023/commit/${sha}"
            git push
          else
            echo "No diff, no push"
          fi
      
